# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cnc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='cnc.proto',
  package='siemens.cnc',
  syntax='proto3',
  serialized_pb=_b('\n\tcnc.proto\x12\x0bsiemens.cnc\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n\x06\x43ncMsg\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08mac_addr\x18\x02 \x01(\t\x12\x0f\n\x07ip_addr\x18\x03 \x01(\t\x12\x0f\n\x07ip_port\x18\x04 \x01(\t\x12$\n\x05param\x18\x05 \x03(\x0b\x32\x15.siemens.cnc.CncParam\"\'\n\x08\x43ncParam\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tP\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CNCMSG = _descriptor.Descriptor(
  name='CncMsg',
  full_name='siemens.cnc.CncMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='siemens.cnc.CncMsg.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mac_addr', full_name='siemens.cnc.CncMsg.mac_addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip_addr', full_name='siemens.cnc.CncMsg.ip_addr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip_port', full_name='siemens.cnc.CncMsg.ip_port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='siemens.cnc.CncMsg.param', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=205,
)


_CNCPARAM = _descriptor.Descriptor(
  name='CncParam',
  full_name='siemens.cnc.CncParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='siemens.cnc.CncParam.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='siemens.cnc.CncParam.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=246,
)

_CNCMSG.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CNCMSG.fields_by_name['param'].message_type = _CNCPARAM
DESCRIPTOR.message_types_by_name['CncMsg'] = _CNCMSG
DESCRIPTOR.message_types_by_name['CncParam'] = _CNCPARAM

CncMsg = _reflection.GeneratedProtocolMessageType('CncMsg', (_message.Message,), dict(
  DESCRIPTOR = _CNCMSG,
  __module__ = 'cnc_pb2'
  # @@protoc_insertion_point(class_scope:siemens.cnc.CncMsg)
  ))
_sym_db.RegisterMessage(CncMsg)

CncParam = _reflection.GeneratedProtocolMessageType('CncParam', (_message.Message,), dict(
  DESCRIPTOR = _CNCPARAM,
  __module__ = 'cnc_pb2'
  # @@protoc_insertion_point(class_scope:siemens.cnc.CncParam)
  ))
_sym_db.RegisterMessage(CncParam)


# @@protoc_insertion_point(module_scope)
